# Generated by Django 3.2.4 on 2021-06-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamfight_tactics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='core_items',
            field=models.TextField(default='items'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comp',
            name='gameplan',
            field=models.TextField(default='strategy'),
            preserve_default=False,
        ),
    ]
